//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Net_Gmap
{
    using System;
    using System.Collections.Generic;
    
    public partial class new_sapsyncqueueExtensionBase
    {
        public System.Guid new_sapsyncqueueId { get; set; }
        public string new_name { get; set; }
        public string new_entityid { get; set; }
        public string new_keyinfor { get; set; }
        public Nullable<System.Guid> new_contact { get; set; }
        public string new_Result { get; set; }
        public string new_Operation { get; set; }
        public string new_address { get; set; }
        public Nullable<System.Guid> new_Account { get; set; }
    }
}
