//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DetectDeuplication.qcrm_OrgService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="AttributeCollection", Namespace="http://schemas.microsoft.com/xrm/2011/Contracts", ItemName="KeyValuePairOfstringanyType")]
    [System.SerializableAttribute()]
    public class AttributeCollection : System.Collections.Generic.List<System.Collections.Generic.KeyValuePair<string, object>> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="FormattedValueCollection", Namespace="http://schemas.microsoft.com/xrm/2011/Contracts", ItemName="KeyValuePairOfstringstring")]
    [System.SerializableAttribute()]
    public class FormattedValueCollection : System.Collections.Generic.List<System.Collections.Generic.KeyValuePair<string, string>> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="RelatedEntityCollection", Namespace="http://schemas.microsoft.com/xrm/2011/Contracts", ItemName="KeyValuePairOfRelationshipEntityCollectionX_PsK4FkN")]
    [System.SerializableAttribute()]
    public class RelatedEntityCollection : System.Collections.Generic.List<System.Collections.Generic.KeyValuePair<Microsoft.Xrm.Sdk.Relationship, Microsoft.Xrm.Sdk.EntityCollection>> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="LocalizedLabelCollection", Namespace="http://schemas.microsoft.com/xrm/2011/Contracts", ItemName="LocalizedLabel")]
    [System.SerializableAttribute()]
    public class LocalizedLabelCollection : System.Collections.Generic.List<Microsoft.Xrm.Sdk.LocalizedLabel> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="EntityReferenceCollection", Namespace="http://schemas.microsoft.com/xrm/2011/Contracts", ItemName="EntityReference")]
    [System.SerializableAttribute()]
    public class EntityReferenceCollection : System.Collections.Generic.List<Microsoft.Xrm.Sdk.EntityReference> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="AttributePrivilegeCollection", Namespace="http://schemas.microsoft.com/xrm/2011/Contracts", ItemName="AttributePrivilege")]
    [System.SerializableAttribute()]
    public class AttributePrivilegeCollection : System.Collections.Generic.List<Microsoft.Xrm.Sdk.AttributePrivilege> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="RelationshipQueryCollection", Namespace="http://schemas.microsoft.com/xrm/2011/Contracts", ItemName="KeyValuePairOfRelationshipQueryBaseX_PsK4FkN")]
    [System.SerializableAttribute()]
    public class RelationshipQueryCollection : System.Collections.Generic.List<System.Collections.Generic.KeyValuePair<Microsoft.Xrm.Sdk.Relationship, Microsoft.Xrm.Sdk.Query.QueryBase>> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="EntityMetadataCollection", Namespace="http://schemas.microsoft.com/xrm/2011/Contracts", ItemName="EntityMetadata")]
    [System.SerializableAttribute()]
    public class EntityMetadataCollection : System.Collections.Generic.List<Microsoft.Xrm.Sdk.Metadata.EntityMetadata> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ParameterCollection", Namespace="http://schemas.microsoft.com/xrm/2011/Contracts", ItemName="KeyValuePairOfstringanyType")]
    [System.SerializableAttribute()]
    public class ParameterCollection : System.Collections.Generic.List<System.Collections.Generic.KeyValuePair<string, object>> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ErrorDetailCollection", Namespace="http://schemas.microsoft.com/xrm/2011/Contracts", ItemName="KeyValuePairOfstringanyType")]
    [System.SerializableAttribute()]
    public class ErrorDetailCollection : System.Collections.Generic.List<System.Collections.Generic.KeyValuePair<string, object>> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="DeletedMetadataCollection", Namespace="http://schemas.microsoft.com/xrm/2011/Metadata/Query", ItemName="KeyValuePairOfDeletedMetadataFiltersArrayOfguidPlUv_PKtF")]
    [System.SerializableAttribute()]
    public class DeletedMetadataCollection : System.Collections.Generic.List<System.Collections.Generic.KeyValuePair<Microsoft.Xrm.Sdk.Metadata.Query.DeletedMetadataFilters, System.Guid[]>> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="OrganizationRequestCollection", Namespace="http://schemas.microsoft.com/xrm/2012/Contracts", ItemName="OrganizationRequest")]
    [System.SerializableAttribute()]
    public class OrganizationRequestCollection : System.Collections.Generic.List<Microsoft.Xrm.Sdk.OrganizationRequest> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="OrganizationResponseCollection", Namespace="http://schemas.microsoft.com/xrm/2012/Contracts", ItemName="ExecuteMultipleResponseItem")]
    [System.SerializableAttribute()]
    public class OrganizationResponseCollection : System.Collections.Generic.List<Microsoft.Xrm.Sdk.ExecuteMultipleResponseItem> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="AuditPartitionDetailCollection", Namespace="http://schemas.microsoft.com/crm/2011/Contracts", ItemName="AuditPartitionDetail")]
    [System.SerializableAttribute()]
    public class AuditPartitionDetailCollection : System.Collections.Generic.List<Microsoft.Crm.Sdk.Messages.AuditPartitionDetail> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CacheItem", Namespace="http://schemas.microsoft.com/crm/2011/Contracts")]
    [System.SerializableAttribute()]
    public partial class CacheItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Key {
            get {
                return this.KeyField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyField, value) != true)) {
                    this.KeyField = value;
                    this.RaisePropertyChanged("Key");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FaultType", Namespace="http://schemas.microsoft.com/crm/2011/Contracts")]
    public enum FaultType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CrmException = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ClrException = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Assertion = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Watson = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="QueryByEntityNameDictionary", Namespace="http://schemas.microsoft.com/crm/2011/Contracts", ItemName="KeyValuePairOfstringQueryBasegUGIFE1S")]
    [System.SerializableAttribute()]
    public class QueryByEntityNameDictionary : System.Collections.Generic.List<System.Collections.Generic.KeyValuePair<string, Microsoft.Xrm.Sdk.Query.QueryBase>> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResetSyncStateInfo", Namespace="http://schemas.microsoft.com/crm/2011/Contracts")]
    [System.SerializableAttribute()]
    public partial class ResetSyncStateInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid[] EntityIdsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ObjectTypeCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid[] EntityIds {
            get {
                return this.EntityIdsField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityIdsField, value) != true)) {
                    this.EntityIdsField = value;
                    this.RaisePropertyChanged("EntityIds");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ObjectTypeCode {
            get {
                return this.ObjectTypeCodeField;
            }
            set {
                if ((this.ObjectTypeCodeField.Equals(value) != true)) {
                    this.ObjectTypeCodeField = value;
                    this.RaisePropertyChanged("ObjectTypeCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SdkMessageProcessingStepImageRegistration", Namespace="http://schemas.microsoft.com/crm/2011/Contracts")]
    [System.SerializableAttribute()]
    public partial class SdkMessageProcessingStepImageRegistration : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] AttributesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EntityAliasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ImageTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessagePropertyNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Attributes {
            get {
                return this.AttributesField;
            }
            set {
                if ((object.ReferenceEquals(this.AttributesField, value) != true)) {
                    this.AttributesField = value;
                    this.RaisePropertyChanged("Attributes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EntityAlias {
            get {
                return this.EntityAliasField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityAliasField, value) != true)) {
                    this.EntityAliasField = value;
                    this.RaisePropertyChanged("EntityAlias");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ImageType {
            get {
                return this.ImageTypeField;
            }
            set {
                if ((this.ImageTypeField.Equals(value) != true)) {
                    this.ImageTypeField = value;
                    this.RaisePropertyChanged("ImageType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessagePropertyName {
            get {
                return this.MessagePropertyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MessagePropertyNameField, value) != true)) {
                    this.MessagePropertyNameField = value;
                    this.RaisePropertyChanged("MessagePropertyName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SdkMessageProcessingStepRegistration", Namespace="http://schemas.microsoft.com/crm/2011/Contracts")]
    [System.SerializableAttribute()]
    public partial class SdkMessageProcessingStepRegistration : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomConfigurationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FilteringAttributesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DetectDeuplication.qcrm_OrgService.SdkMessageProcessingStepImageRegistration[] ImagesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid ImpersonatingUserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int InvocationSourceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ModeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PluginTypeFriendlyNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PluginTypeNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrimaryEntityNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SecondaryEntityNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SupportedDeploymentField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomConfiguration {
            get {
                return this.CustomConfigurationField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomConfigurationField, value) != true)) {
                    this.CustomConfigurationField = value;
                    this.RaisePropertyChanged("CustomConfiguration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FilteringAttributes {
            get {
                return this.FilteringAttributesField;
            }
            set {
                if ((object.ReferenceEquals(this.FilteringAttributesField, value) != true)) {
                    this.FilteringAttributesField = value;
                    this.RaisePropertyChanged("FilteringAttributes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DetectDeuplication.qcrm_OrgService.SdkMessageProcessingStepImageRegistration[] Images {
            get {
                return this.ImagesField;
            }
            set {
                if ((object.ReferenceEquals(this.ImagesField, value) != true)) {
                    this.ImagesField = value;
                    this.RaisePropertyChanged("Images");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ImpersonatingUserId {
            get {
                return this.ImpersonatingUserIdField;
            }
            set {
                if ((this.ImpersonatingUserIdField.Equals(value) != true)) {
                    this.ImpersonatingUserIdField = value;
                    this.RaisePropertyChanged("ImpersonatingUserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int InvocationSource {
            get {
                return this.InvocationSourceField;
            }
            set {
                if ((this.InvocationSourceField.Equals(value) != true)) {
                    this.InvocationSourceField = value;
                    this.RaisePropertyChanged("InvocationSource");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageName {
            get {
                return this.MessageNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageNameField, value) != true)) {
                    this.MessageNameField = value;
                    this.RaisePropertyChanged("MessageName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Mode {
            get {
                return this.ModeField;
            }
            set {
                if ((this.ModeField.Equals(value) != true)) {
                    this.ModeField = value;
                    this.RaisePropertyChanged("Mode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PluginTypeFriendlyName {
            get {
                return this.PluginTypeFriendlyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PluginTypeFriendlyNameField, value) != true)) {
                    this.PluginTypeFriendlyNameField = value;
                    this.RaisePropertyChanged("PluginTypeFriendlyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PluginTypeName {
            get {
                return this.PluginTypeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PluginTypeNameField, value) != true)) {
                    this.PluginTypeNameField = value;
                    this.RaisePropertyChanged("PluginTypeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PrimaryEntityName {
            get {
                return this.PrimaryEntityNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PrimaryEntityNameField, value) != true)) {
                    this.PrimaryEntityNameField = value;
                    this.RaisePropertyChanged("PrimaryEntityName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SecondaryEntityName {
            get {
                return this.SecondaryEntityNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SecondaryEntityNameField, value) != true)) {
                    this.SecondaryEntityNameField = value;
                    this.RaisePropertyChanged("SecondaryEntityName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Stage {
            get {
                return this.StageField;
            }
            set {
                if ((this.StageField.Equals(value) != true)) {
                    this.StageField = value;
                    this.RaisePropertyChanged("Stage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SupportedDeployment {
            get {
                return this.SupportedDeploymentField;
            }
            set {
                if ((this.SupportedDeploymentField.Equals(value) != true)) {
                    this.SupportedDeploymentField = value;
                    this.RaisePropertyChanged("SupportedDeployment");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SyncAction", Namespace="http://schemas.microsoft.com/crm/2011/Contracts")]
    public enum SyncAction : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Insert = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Delete = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Update = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/Contracts/Services", ConfigurationName="qcrm_OrgService.IOrganizationService")]
    public interface IOrganizationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/Cre" +
            "ate", ReplyAction="http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/Cre" +
            "ateResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.Xrm.Sdk.OrganizationServiceFault), Action="http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/Cre" +
            "ateOrganizationServiceFaultFault", Name="OrganizationServiceFault", Namespace="http://schemas.microsoft.com/xrm/2011/Contracts")]
        System.Guid Create(Microsoft.Xrm.Sdk.Entity entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/Ret" +
            "rieve", ReplyAction="http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/Ret" +
            "rieveResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.Xrm.Sdk.OrganizationServiceFault), Action="http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/Ret" +
            "rieveOrganizationServiceFaultFault", Name="OrganizationServiceFault", Namespace="http://schemas.microsoft.com/xrm/2011/Contracts")]
        Microsoft.Xrm.Sdk.Entity Retrieve(string entityName, System.Guid id, Microsoft.Xrm.Sdk.Query.ColumnSet columnSet);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/Upd" +
            "ate", ReplyAction="http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/Upd" +
            "ateResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.Xrm.Sdk.OrganizationServiceFault), Action="http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/Upd" +
            "ateOrganizationServiceFaultFault", Name="OrganizationServiceFault", Namespace="http://schemas.microsoft.com/xrm/2011/Contracts")]
        void Update(Microsoft.Xrm.Sdk.Entity entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/Del" +
            "ete", ReplyAction="http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/Del" +
            "eteResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.Xrm.Sdk.OrganizationServiceFault), Action="http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/Del" +
            "eteOrganizationServiceFaultFault", Name="OrganizationServiceFault", Namespace="http://schemas.microsoft.com/xrm/2011/Contracts")]
        void Delete(string entityName, System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/Exe" +
            "cute", ReplyAction="http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/Exe" +
            "cuteResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.Xrm.Sdk.OrganizationServiceFault), Action="http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/Exe" +
            "cuteOrganizationServiceFaultFault", Name="OrganizationServiceFault", Namespace="http://schemas.microsoft.com/xrm/2011/Contracts")]
        Microsoft.Xrm.Sdk.OrganizationResponse Execute(Microsoft.Xrm.Sdk.OrganizationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/Ass" +
            "ociate", ReplyAction="http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/Ass" +
            "ociateResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.Xrm.Sdk.OrganizationServiceFault), Action="http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/Ass" +
            "ociateOrganizationServiceFaultFault", Name="OrganizationServiceFault", Namespace="http://schemas.microsoft.com/xrm/2011/Contracts")]
        void Associate(string entityName, System.Guid entityId, Microsoft.Xrm.Sdk.Relationship relationship, DetectDeuplication.qcrm_OrgService.EntityReferenceCollection relatedEntities);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/Dis" +
            "associate", ReplyAction="http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/Dis" +
            "associateResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.Xrm.Sdk.OrganizationServiceFault), Action="http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/Dis" +
            "associateOrganizationServiceFaultFault", Name="OrganizationServiceFault", Namespace="http://schemas.microsoft.com/xrm/2011/Contracts")]
        void Disassociate(string entityName, System.Guid entityId, Microsoft.Xrm.Sdk.Relationship relationship, DetectDeuplication.qcrm_OrgService.EntityReferenceCollection relatedEntities);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/Ret" +
            "rieveMultiple", ReplyAction="http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/Ret" +
            "rieveMultipleResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Microsoft.Xrm.Sdk.OrganizationServiceFault), Action="http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/Ret" +
            "rieveMultipleOrganizationServiceFaultFault", Name="OrganizationServiceFault", Namespace="http://schemas.microsoft.com/xrm/2011/Contracts")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Microsoft.Xrm.Sdk.Query.QueryExpression))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Microsoft.Xrm.Sdk.Query.QueryByAttribute))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Microsoft.Xrm.Sdk.Query.FetchExpression))]
        Microsoft.Xrm.Sdk.EntityCollection RetrieveMultiple(Microsoft.Xrm.Sdk.Query.QueryBase query);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOrganizationServiceChannel : DetectDeuplication.qcrm_OrgService.IOrganizationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OrganizationServiceClient : System.ServiceModel.ClientBase<DetectDeuplication.qcrm_OrgService.IOrganizationService>, DetectDeuplication.qcrm_OrgService.IOrganizationService {
        
        public OrganizationServiceClient() {
        }
        
        public OrganizationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OrganizationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrganizationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrganizationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Guid Create(Microsoft.Xrm.Sdk.Entity entity) {
            return base.Channel.Create(entity);
        }
        
        public Microsoft.Xrm.Sdk.Entity Retrieve(string entityName, System.Guid id, Microsoft.Xrm.Sdk.Query.ColumnSet columnSet) {
            return base.Channel.Retrieve(entityName, id, columnSet);
        }
        
        public void Update(Microsoft.Xrm.Sdk.Entity entity) {
            base.Channel.Update(entity);
        }
        
        public void Delete(string entityName, System.Guid id) {
            base.Channel.Delete(entityName, id);
        }
        
        public Microsoft.Xrm.Sdk.OrganizationResponse Execute(Microsoft.Xrm.Sdk.OrganizationRequest request) {
            return base.Channel.Execute(request);
        }
        
        public void Associate(string entityName, System.Guid entityId, Microsoft.Xrm.Sdk.Relationship relationship, DetectDeuplication.qcrm_OrgService.EntityReferenceCollection relatedEntities) {
            base.Channel.Associate(entityName, entityId, relationship, relatedEntities);
        }
        
        public void Disassociate(string entityName, System.Guid entityId, Microsoft.Xrm.Sdk.Relationship relationship, DetectDeuplication.qcrm_OrgService.EntityReferenceCollection relatedEntities) {
            base.Channel.Disassociate(entityName, entityId, relationship, relatedEntities);
        }
        
        public Microsoft.Xrm.Sdk.EntityCollection RetrieveMultiple(Microsoft.Xrm.Sdk.Query.QueryBase query) {
            return base.Channel.RetrieveMultiple(query);
        }
    }
}
